[package]
name = "aethel-common"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { workspace = true }
libc = "0.2.153"
tonic = "0.11"
prost = "0.12"
prost-types = "0.12"
prost-wkt-types = { version = "0.5.0", optional = true }

[build-dependencies]
tonic-build = "0.11"